//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.WinformMvc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.WinformMvc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while executing the action [{0}], check the underlying implementation : TECHNICAL_DETAIL [{1}] ..
        /// </summary>
        internal static string ActionExecutionException {
            get {
                return ResourceManager.GetString("ActionExecutionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should specified the forwarded controller..
        /// </summary>
        internal static string ActionRequiredException {
            get {
                return ResourceManager.GetString("ActionRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should at least provide a controller type or a view name..
        /// </summary>
        internal static string ArgumentMissingException {
            get {
                return ResourceManager.GetString("ArgumentMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Argument should not be null.
        /// </summary>
        internal static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller [{0}] is not configured. Check the controller manager configurations..
        /// </summary>
        internal static string ControllerMissingException {
            get {
                return ResourceManager.GetString("ControllerMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller {0} does not inherit from IController.
        /// </summary>
        internal static string IncorrectControllerTypeException {
            get {
                return ResourceManager.GetString("IncorrectControllerTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not inherit from Exception..
        /// </summary>
        internal static string IncorrectExceptionTypeException {
            get {
                return ResourceManager.GetString("IncorrectExceptionTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session is already initialized.
        /// </summary>
        internal static string InitializedSessionException {
            get {
                return ResourceManager.GetString("InitializedSessionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key {0} doesn&apos;t exist.
        /// </summary>
        internal static string KeyMissingException {
            get {
                return ResourceManager.GetString("KeyMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method should be implemented.
        /// </summary>
        internal static string NotImplementedMethodException {
            get {
                return ResourceManager.GetString("NotImplementedMethodException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view [{0}] is not configured. Check the controller manager configurations..
        /// </summary>
        internal static string ViewMissingException {
            get {
                return ResourceManager.GetString("ViewMissingException", resourceCulture);
            }
        }
    }
}
